repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
    - id: shellcheck
      args: [--severity=warning]
      files: ^ws_.*$

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.23.1
  hooks:
    - id: gitleaks
