#!/bin/bash

printf 'Killing all running containers... '
for i in $(docker ps | awk '{print $1}' | grep -vi container); do docker kill $i || break; done
printf 'done\n'

printf 'Clearing down all containers... '
for i in $(docker ps --all | awk '{print $1}' | grep -vi container); do docker rm $i || break; done
printf 'done\n'

printf 'Clearing down all images... '
for i in $(docker images | awk '{print $3}' | grep -vi image); do docker rmi $i --force || break; done
printf 'done\n'
