#!/bin/bash

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

for i in $(echo $PATH | sed "s/:/ /g"); do
    if  [ -d $i ]; then
        printf "%s\n" "${grn}'$i' exists...${end}"
    else
        printf "%s\n" "${red}'$i' does not exist...${end}"
    fi
done
