#!/bin/bash

red=$'\e[1;31m'
grn=$'\e[1;32m'
end=$'\e[0m'

for i in ${PATH//:/ }; do
    if [ -d "$i" ]; then
        printf "%s\n" "${grn}'$i' exists...${end}"
    else
        printf "%s\n" "${red}'$i' does not exist...${end}"
    fi
done
